apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${CACHE_CLAIM_NAME}
  namespace: '${NAMESPACE@microservice-config}'
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"
  selector:
    matchLabels:
      service: "${CACHE_SERVICE_NAME@microservice-resources-config}"
