apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${QUEUE_CLAIM_NAME}
  namespace: '${NAMESPACE@microservice-config}'
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"
  selector:
    matchLabels:
      service: "${QUEUE_SERVICE_NAME@microservice-resources-config}"
