apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: '${CACHE_STATEFUL_NAME}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    moduleid: microservice-resources-realm
    version: 1.70.2-master
spec:
  serviceName: '${CACHE_SERVICE_NAME@microservice-resources-config}'
  selector:
    matchLabels:
      app: '${CACHE_STATEFUL_NAME}'
  replicas: 1
  template:
    metadata:
      labels:
        app: '${CACHE_STATEFUL_NAME}'
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        -
          name: data
          image: 'redis:3.2-alpine'
          args:
            - '--requirepass'
            - $(CACHE_SECRET_PASSWORD)
            - '--appendonly'
            - yes
            - '--save'
            - '900'
            - '1'
            - '--save'
            - '30'
            - '1'
          env:
            -
              name: CACHE_SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: '${CACHE_SECRET_NAME@microservice-resources-config}'
                  key: password
          ports:
            -
              containerPort: '${CACHE_INTERNAL_PORT@microservice-resources-config}'
          volumeMounts:
            -
              name: data
              mountPath: /data
      volumes:
        -
          name: data
          persistentVolumeClaim:
            claimName: '${CACHE_CLAIM_NAME}'
