apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "${CACHE_VOLUME_NAME}"
  namespace: ${NAMESPACE@microservice-config}
  labels:
    service: "${CACHE_SERVICE_NAME@microservice-resources-config}"
spec:
  capacity:
    storage: "100Mi"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: local-storage
  hostPath:
    path: /home/docker/production/${HOST@microservice-config}/volumes/${CACHE_VOLUME_NAME}
