apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "${DATA_VOLUME_NAME}"
  namespace: ${NAMESPACE@microservice-config}
  labels:
    service: "${DATA_SERVICE_NAME@microservice-resources-config}"
spec:
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadWriteOnce"
  awsElasticBlockStore:
    fsType: "ext4"
    volumeID: "vol-0572afea6012336e4"
