apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "${DATA_VOLUME_NAME}"
  namespace: ${NAMESPACE@microservice-config}
  labels:
    service: "${DATA_SERVICE_NAME@microservice-resources-config}"
    fsOwner: "1001"
    fsGroup: "0"
    fsMode: "775"
spec:
  capacity:
    storage: "500Mi"
  accessModes:
    - "ReadWriteOnce"
  storageClassName: local-storage
  hostPath:
    path: /home/docker/production/${HOST@microservice-config}/volumes/${DATA_VOLUME_NAME}
