apiVersion: apps/v1
kind: Deployment
metadata:
  name: '${WEB_DEPLOYMENT_NAME}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    app: '${WEB_DEPLOYMENT_NAME}'
    moduleid: microservice-resources-realm
    version: 1.70.6-master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: '${WEB_DEPLOYMENT_NAME}'
  template:
    metadata:
      labels:
        app: '${WEB_DEPLOYMENT_NAME}'
    spec:
      containers:
        -
          name: app
          image: 'repoflow/microservice-resources-container:1.70.1-master'
          env:
            -
              name: HOST
              value: '${HOST@microservice-config}'
            -
              name: RESOURCES_BASE_ROUTE
              value: '${WEB_BASE_ROUTE@microservice-resources-config}'
            -
              name: RESOURCES_INTERNAL_PORT
              value: '${WEB_INTERNAL_PORT@microservice-resources-config}'
          ports:
            -
              containerPort: '${WEB_INTERNAL_PORT@microservice-resources-config}'
